###################################################
#         __                     ____             #
#    ____/ /___ ____  ____ ___  / __ \____  _____ #
#   / __  / __ `/ _ \/ __ `__ \/ / / / __ \/ ___/ #
#  / /_/ / /_/ /  __/ / / / / / /_/ / / / (__  )  #
#  \__,_/\__,_/\___/_/ /_/ /_/\____/_/ /_/____/   #
###################################################

# How many new lines will be created when you run /clearchat
clearchat-line-inserts: 71

# TPS checker, each value should never be higher than 20, as a server TPS will only go as high as 20
tps:
  1m: 18
  5m: 19
  15m: 19