###################################################
#         __                     ____             #
#    ____/ /___ ____  ____ ___  / __ \____  _____ #
#   / __  / __ `/ _ \/ __ `__ \/ / / / __ \/ ___/ #
#  / /_/ / /_/ /  __/ / / / / / /_/ / / / (__  )  #
#  \__,_/\__,_/\___/_/ /_/ /_/\____/_/ /_/____/   #
###################################################

# How many new lines will be created when you run /clearchat
# Default: 100
clearchat-line-inserts: 100

# TPS checker, each value should never be higher than 20, as a server TPS will only go as high as 20
# Console messages are the normal messages telling the console that the server is running normally. This helps cut down
# on console spam if left false. If the server is unstable it will still broadcast a message.
tps:
  5s: 19.5
  1m: 19
  5m: 19
  15m: 19
  console-messages: false

# OpTool configuration, if enabled this will enable the usage of OpTool.
# There can also be a database attached to it if you want to log who ran commands to op or deop
# players
optool: true
  use-db: false
  user: ""
  pass: ""
  url: ""