name: daem0ns
version: @version@
main: unlucky.daem0ns.Main
api-version: 1.16
authors: [ unlucky_dem0n ]

commands:
  clearchat:
    aliases: [ cc ]
    description: Clears chat.
    permission: daem0ns.clearchat
    usage: /cc
  hide:
    aliases: [ ]
    description: Chat.
  muteall:
    aliases: [ ]
    description: Mutes the server.
    permission: daem0ns.muteall
    usage: /muteall

permissions:
  daem0ns.*:
    description: Gives all daem0ns permissions and commands
    children:
      daem0ns.clearshat: true
      daem0ns.muteall: true
  daem0ns.muteall:
    description: Gives permission to mute the whole server
    default: false
  daem0ns.clearchat:
    description: Gives permission to clear the chat
    default: false