name: daem0ns
version: 0.2
main: io.garrettsummerfi3ld.daem0ns.Main
api-version: 1.17
authors: [ unlucky_dem0n ]

commands:
  clearchat:
    aliases: [ cc ]
    description: Clears chat.
    permission: daem0ns.clearchat
    usage: /cc
  hide:
    aliases: [ hc ]
    description: Broadcasts a message to the server without the username attached.
    permission: daem0ns.hide
    usage: /hide
  muteall:
    aliases: [ ]
    description: Mutes the server.
    permission: daem0ns.muteall
    usage: /muteall

permissions:
  daem0ns.*:
    default: op
    description: Gives all daem0ns permissions and commands
    children:
      daem0ns.clearshat: true
      daem0ns.muteall: true
      daemons.muteall.bypass: true
      daem0ns.hide: true
      daem0ns.perfreport: true
  daem0ns.muteall:
    description: Gives permission to mute the whole server
    default: op
    daem0ns.muteall.bypass:
      description: Gives override permission to chat while server is muted
      default: op
  daem0ns.clearchat:
    description: Gives permission to clear the chat
    default: op
  daem0ns.hide:
    description: Gives permission to send an untagged message
    default: false
  daem0ns.perfreport:
    description: Gives permission to see performance reporting from the internal schedulers.
    default: op
